version: 2.1

defaults: &defaults
  working_directory: ~/truemail-crystal-client
  docker:
    - image: crystallang/crystal:1.3.2

references:
  restore_shards_cache: &restore_shards_cache
    restore_cache:
      keys:
        - shards-cache-v1-{{ checksum "shard.yml" }}

  shards_intall: &shards_intall
    run:
      name: Installing shards
      command: shards install

  save_shards_cache: &save_shards_cache
    save_cache:
      key: shards-cache-v1-{{ checksum "shard.yml" }}
      paths:
        - ./shards-cache

jobs:
  linters:
    <<: *defaults

    steps:
      - checkout

      - <<: *restore_shards_cache
      - <<: *shards_intall
      - <<: *save_shards_cache

      - run:
          name: Running ameba
          command: |
            bin/ameba
  tests:
    <<: *defaults

    steps:
      - checkout

      - <<: *restore_shards_cache
      - <<: *shards_intall
      - <<: *save_shards_cache

      - run:
          name: Running tests
          command: |
            crystal spec

workflows:
  build_and_test:
    jobs:
      - linters
      - tests
